import { z } from "zod";

const envSchema = z.object({
  NEXT_PUBLIC_APP_NAME: z.string().min(1).default("Радар кейсів SPROF"),
  NEXT_PUBLIC_APP_URL: z.string().url().default("http://localhost:3000"),
  NEXT_PUBLIC_SUPABASE_URL: z.string().url().or(z.literal("")).default(""),
  NEXT_PUBLIC_SUPABASE_ANON_KEY: z.string().or(z.literal("")).default(""),
  SUPABASE_SERVICE_ROLE_KEY: z.string().or(z.literal("")).default(""),
  ADMIN_EMAIL: z.string().email().default("epkram@gmail.com"),
  GOOGLE_SHEETS_CLIENT_EMAIL: z.string().or(z.literal("")).default(""),
  GOOGLE_SHEETS_PRIVATE_KEY: z.string().or(z.literal("")).default(""),
  GOOGLE_SHEETS_PROJECT_ID: z.string().or(z.literal("")).default(""),
  EMAIL_PROVIDER: z.string().default("smtp_or_api"),
  EMAIL_FROM: z.string().default("Радар кейсів SPROF <no-reply@sprof.ua>"),
  SMTP_HOST: z.string().or(z.literal("")).default(""),
  SMTP_PORT: z.coerce.string().default("587"),
  SMTP_USER: z.string().or(z.literal("")).default(""),
  SMTP_PASSWORD: z.string().or(z.literal("")).default(""),
  EMAIL_API_KEY: z.string().or(z.literal("")).default(""),
  TELEGRAM_BOT_TOKEN: z.string().or(z.literal("")).default(""),
  TELEGRAM_WEBHOOK_SECRET: z.string().or(z.literal("")).default(""),
  TELEGRAM_BOT_USERNAME: z.string().or(z.literal("")).default(""),
  CRON_SECRET: z.string().or(z.literal("")).default(""),
});

export const env = envSchema.parse({
  NEXT_PUBLIC_APP_NAME: process.env.NEXT_PUBLIC_APP_NAME,
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
  NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
  ADMIN_EMAIL: process.env.ADMIN_EMAIL,
  GOOGLE_SHEETS_CLIENT_EMAIL: process.env.GOOGLE_SHEETS_CLIENT_EMAIL,
  GOOGLE_SHEETS_PRIVATE_KEY: process.env.GOOGLE_SHEETS_PRIVATE_KEY,
  GOOGLE_SHEETS_PROJECT_ID: process.env.GOOGLE_SHEETS_PROJECT_ID,
  EMAIL_PROVIDER: process.env.EMAIL_PROVIDER,
  EMAIL_FROM: process.env.EMAIL_FROM,
  SMTP_HOST: process.env.SMTP_HOST,
  SMTP_PORT: process.env.SMTP_PORT,
  SMTP_USER: process.env.SMTP_USER,
  SMTP_PASSWORD: process.env.SMTP_PASSWORD,
  EMAIL_API_KEY: process.env.EMAIL_API_KEY,
  TELEGRAM_BOT_TOKEN: process.env.TELEGRAM_BOT_TOKEN,
  TELEGRAM_WEBHOOK_SECRET: process.env.TELEGRAM_WEBHOOK_SECRET,
  TELEGRAM_BOT_USERNAME: process.env.TELEGRAM_BOT_USERNAME,
  CRON_SECRET: process.env.CRON_SECRET,
});
